### ISSUE TITLE
when initial failed, not checked error, panic occurred

### ISSUE THREAD

**Issue by duguying** [akamai/AkamaiOPEN-edgegrid-golang#55]
https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/f85d9fba0c117ecabe725f3bf31a45ddfb182d85/papi-v1/search.go#L51

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x887de9]

goroutine 16199 [running]:
sparta-admin/storage-server/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/client-v1.IsError(...)
	/root/go/src/sparta-admin/storage-server/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/client-v1/errors.go:106
sparta-admin/storage-server/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1.Search(0xeaaaaf, 0xc, 0x0, 0x0, 0x987bb8, 0xd93c20, 0xc00023ade0)
	/root/go/src/sparta-admin/storage-server/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/search.go:53 +0x179
sparta-admin/storage-server/modules/akamai.(*AkaApi).CreateDomain(0xc0002df450, 0xc000e5ad42, 0xe, 0xc000e5b2b0, 0xc, 0xc000e5b2a0, 0x9, 0x0, 0xc0003dd980)
	/root/go/src/sparta-admin/storage-server/modules/akamai/aka.go:454 +0x139
sparta-admin/storage-server/service/server.(*SpartaAdminServerImpl).BusinessActiveAkamai.func1(0xc00034ee80, 0xc000e5ad42, 0xe, 0xc0003e4ea0, 0xc000b86da0)
	/root/go/src/sparta-admin/storage-server/service/server/sparta.go:545 +0x7d
created by sparta-admin/storage-server/service/server.(*SpartaAdminServerImpl).BusinessActiveAkamai
	/root/go/src/sparta-admin/storage-server/service/server/sparta.go:542 +0x399
```

**Comment by zstlaw** [comment]
So we have re-written pretty much the whole papi library.  We fixed a bunch of bugs in v1.0.0 and we moved to v2 where we improved logic and flow and error messaging quite a bit.  The v1 line is for current tools while v2 has significant refactoring of most interfaces.
